1.创建一维数组，和二维数组，打印维度、形状、数量、类型

In [ ]:
impo"$"$1""t numpy as np
arr1 = np.array([6,-2,-7,2,8,-2,1])
arr2 = np.array([[1,3,5],[2,4,6]])
print(arr1)
print(arr2)

print("维度是,n",arr1.ndim)
print(arr2.ndim)

print("形状是：,n",np.shape(arr1))
print(arr2.shape)

print("数量是,n",arr1.size)
print(arr2.size)

print("类型是,n",arr2.dtype)

[ 6 -2 -7  2  8 -2  1]
[[1 3 5]
 [2 4 6]]
维度是
 1
2
形状是：
 (7,)
(2, 3)
数量是
 7
6
类型是
 int32


2.分别创建1个6个0和6个1的一维数组，创建一个10-20的偶数数组

In [ ]:
arr_zero =np.array([0]*6)
arr_ones = np.array([1]*6)
arr_oushu = np.array(list(range(10,21,2)))

print(arr_zero,",n",arr_ones,",n",arr_oushu)

[0 0 0 0 0 0] 
 [1 1 1 1 1 1] 
 [10 12 14 16 18 20]


3.创建一个数组3,arr3，包括上面的数字，并对其排序

In [ ]:
arr3 = np.concatenate([arr1,arr_oushu])
print(arr3)
arr3 =np.sort(arr3)
print(arr3)

print(arr3[2])
print(arr3[-12])
print(arr3[2:4]+arr3[6:8])

[ 6 -2 -7  2  8 -2  1 10 12 14 16 18 20]
[-7 -2 -2  1  2  6  8 10 12 14 16 18 20]
-2
-2
[ 6 11]


4.打印arr3的最大值，最小值，和，平均值
筛选出数组中大于2小于16的值

In [ ]:
print(arr3.max(),",n",arr3.min(),",n",arr3.sum(),",n",arr3.mean())
a = arr3>2
b = arr3<16
print(arr3[a&b])

20 
 -7 
 96 
 7.384615384615385
[ 6  8 10 12 14]


# Pandas

创建一个s1的series，包含-1.2,3.7,2.5,-8.2,6.3 ,打印索引及数值，创建s2,索引1-5，数值5-1

In [ ]:
import pandas as pd
s1=pd.Series([-1.2,3.7,2.5,-8.2,6.3])
print(s1.index,"\n",s1.values)
s2 = pd.Series(np.arange(5,0,-1),index = np.arange(1,6))
print(s2)
print('位置索引第二个元素',s2.iloc[1])
print("index = 2的数值",s2[2])
print(s2.index,s2.values)


RangeIndex(start=0, stop=5, step=1) 
 [-1.2  3.7  2.5 -8.2  6.3]
1    5
2    4
3    3
4    2
5    1
dtype: int32
位置索引第二个元素 4
index = 2的数值 4
Index([1, 2, 3, 4, 5], dtype='int32') [5 4 3 2 1]


标签对应5-3的元素

In [ ]:
print(s2.loc[5:3:-1])

5    1
4    2
3    3
dtype: int32


创建一个字典s3，a,b,c,d,e,对应82,93,91,78,68
把b改为95
输出>80且<90的元素

In [85]:
a1 = ["a","b","c","d","e"]
a2 = [82,93,91,78,68]
a3 = dict(zip(a1,a2))
s3 = pd.Series(a3)
print(s3.index,s3.values)
s3["b"] = 95
print(s3.iloc[(s3.values>0) & (s3.values<90)])

Index(['a', 'b', 'c', 'd', 'e'], dtype='object') [82 93 91 78 68]
a    82
d    78
e    68
dtype: int64
