1.创建一维数组，和二维数组，打印维度、形状、数量、类型

impo"$"$1""t numpy as np
arr1 = np.array([6,-2,-7,2,8,-2,1])
arr2 = np.array([[1,3,5],[2,4,6]])
print(arr1)
print(arr2)

print("维度是,n",arr1.ndim)
print(arr2.ndim)

print("形状是：,n",np.shape(arr1))
print(arr2.shape)

print("数量是,n",arr1.size)
print(arr2.size)

print("类型是,n",arr2.dtype)

In [ ]:
import numpy as np
arr1 = np.array([6,-2,-7,2,8,-2,1])
arr2 = np.array([[1,3,5],[2,4,6]])
print(arr1)
print(arr2)

print("维度是,n",arr1.ndim)
print(arr2.ndim)

print("形状是：,n",np.shape(arr1))
print(arr2.shape)

print("数量是,n",arr1.size)
print(arr2.size)

print("类型是,n",arr2.dtype)

[ 6 -2 -7  2  8 -2  1]
[[1 3 5]
 [2 4 6]]
维度是
 1
2
形状是：
 (7,)
(2, 3)
数量是
 7
6
类型是
 int32


arr_zero =np.array([0]*6)
arr_ones = np.array([1]*6)
arr_oushu = np.array(list(range(10,21,2)))

print(arr_zero,",n",arr_ones,",n",arr_oushu)

In [ ]:
3.创建一个数组3,arr3，包括上面的数字，并对其排序

[0 0 0 0 0 0] 
 [1 1 1 1 1 1] 
 [10 12 14 16 18 20]


arr3 = np.concatenate([arr1,arr_oushu])
print(arr3)
arr3 =np.sort(arr3)
print(arr3)

print(arr3[2])
print(arr3[-12])
print(arr3[2:4]+arr3[6:8])

In [ ]:
arr3 = np.concatenate([arr1,arr_oushu])
print(arr3)
arr3 =np.sort(arr3)
print(arr3)

print(arr3[2])
print(arr3[-12])
print(arr3[2:4]+arr3[6:8])

[ 6 -2 -7  2  8 -2  1 10 12 14 16 18 20]
[-7 -2 -2  1  2  6  8 10 12 14 16 18 20]
-2
-2
[ 6 11]


4.打印arr3的最大值,最小值，和，平均值
筛选出数组中大于2小于16的值

In [ ]:
print(arr3.max(),",n",arr3.min(),",n",arr3.sum(),",n",arr3.mean())
a = arr3>2
b = arr3<16
print(arr3[a&b])

20 
 -7 
 96 
 7.384615384615385
[ 6  8 10 12 14]


# Pandas

## pandas series


创建一个s1的series，包含-1.2,3.7,2.5,-8.2,6.3 ,打印索引及数值,创建s2,索引1-5,数值5-1

In [ ]:
import pandas as pd
s1=pd.Series([-1.2,3.7,2.5,-8.2,6.3])
print(s1.index,"\n",s1.values)
s2 = pd.Series(np.arange(5,0,-1),index = np.arange(1,6))
print(s2)
print('位置索引第二个元素',s2.iloc[1])
print("index = 2的数值",s2[2])
print(s2.index,s2.values)


RangeIndex(start=0, stop=5, step=1) 
 [-1.2  3.7  2.5 -8.2  6.3]
1    5
2    4
3    3
4    2
5    1
dtype: int32
位置索引第二个元素 4
index = 2的数值 4
Index([1, 2, 3, 4, 5], dtype='int32') [5 4 3 2 1]


标签对应5-3的元素

In [ ]:
print(s2.loc[5:3:-1])

5    1
4    2
3    3
dtype: int32


创建一个字典s3,a,b,c,d,e,对应82,93,91,78,68
把b改为95
输出>80且<90的元素

In [ ]:
a1 = ["a","b","c","d","e"]
a2 = [82,93,91,78,68]
a3 = dict(zip(a1,a2))
s3 = pd.Series(a3)
print(s3.index,s3.values)
s3["b"] = 95
print(s3.iloc[(s3.values>0) & (s3.values<90)])

## pandas apply

创建一个s1,s2

In [3]:
import pandas as pd
s1 = pd.Series([92,67,70,88,76],index=["小明",'小红','小杰','小丽','小华'])
s2 = pd.Series([95,85,60,79,76],index = ['小明','小杰','小宇','小娟','小彤'])
print(s1,s2)


小明    92
小红    67
小杰    70
小丽    88
小华    76
dtype: int64 小明    95
小杰    85
小宇    60
小娟    79
小彤    76
dtype: int64


按照索引相加,无法找的值用0代替
输出s1的,最大值,最小值,平均值,标准差

In [ ]:
s1.add(s2,fill_value=0)
s1.max(),s1.min(),s1.mean(),s1.std()
print(s1.describe())

count     5.000000
mean     78.600000
std      10.990905
min      67.000000
25%      70.000000
50%      76.000000
75%      88.000000
max      92.000000
dtype: float64


s1的成绩+5,然后把成绩转化为等级

In [ ]:
s1=s1+5
print(s1)
def grad_to(score):
    if score>90:
        return "A"
    elif score>60:
        return 'B'
    else:
        return'C'
print(s1.apply(grad_to))

小明    97
小红    72
小杰    75
小丽    93
小华    81
dtype: int64
小明    A
小红    B
小杰    B
小丽    A
小华    B
dtype: object


## pandas dateframe

### 查看

In [16]:
import pandas as pd
name = pd.Series(["小陈","小李","小王","小张","小赵","小周"],index =['001','002','003','004','005','006'] )
gender = pd.Series(["女","女","男","男","女","男"],index = ['006','005','004','003','002','001'])
height = pd.Series([172.5, 168.0, 178.2, 181.3, 161.7],index = ["001", "002", "003", "004", "005"])

students = pd.DataFrame({"性别":gender,"身高":height,'姓名':name})
print(students)
print(students.index,students.columns) #打印列名
print(students.T) #转置
print(students['身高'])
print(students[['身高','性别']])


    性别     身高  姓名
001  男  172.5  小陈
002  女  168.0  小李
003  男  178.2  小王
004  男  181.3  小张
005  女  161.7  小赵
006  女    NaN  小周
Index(['001', '002', '003', '004', '005', '006'], dtype='object') Index(['性别', '身高', '姓名'], dtype='object')
      001    002    003    004    005  006
性别      男      女      男      男      女    女
身高  172.5  168.0  178.2  181.3  161.7  NaN
姓名     小陈     小李     小王     小张     小赵   小周
001    172.5
002    168.0
003    178.2
004    181.3
005    161.7
006      NaN
Name: 身高, dtype: float64
        身高 性别
001  172.5  男
002  168.0  女
003  178.2  男
004  181.3  男
005  161.7  女
006    NaN  女
性别        男
身高    178.2
姓名       小王
Name: 003, dtype: object


In [41]:
print(students.loc['003'])
print(students['身高'].loc["005"])
print(students[['姓名','身高']].loc[['003','005'],:])
print(students.loc[['003','005']])
print(students[(students['身高']>160) &(students['性别']=='女')])
print(students.iloc[0:5,:])


性别        男
身高    178.2
姓名       小王
Name: 003, dtype: object
161.7
     姓名     身高
003  小王  178.2
005  小赵  161.7
    性别     身高  姓名
003  男  178.2  小王
005  女  161.7  小赵
    性别     身高  姓名
002  女  168.0  小李
005  女  161.7  小赵
    性别     身高  姓名
001  男  172.5  小陈
002  女  168.0  小李
003  男  178.2  小王
004  男  181.3  小张
005  女  161.7  小赵


### 操作

创建一个名为students的DataFrame，包含数据如下：
{"001": {"姓名": "小陈", "考试1": 85, "考试2": 95, "考试3": 92},
 "002": {"姓名": "小李", "考试1": 91, "考试2": 92, "考试3": 94},
 "003": {"姓名": "小王", "考试1": 86, "考试2": 81, "考试3": 89},
 "004": {"姓名": "小张", "考试1": 79, "考试2": 89, "考试3": 95},
 "005": {"姓名": "小赵", "考试1": 96, "考试2": 91, "考试3": 91},
 "006": {"姓名": "小周", "考试1": 81, "考试2": 89, "考试3": 92} }
 1.给students增加一列考试4，数据依次为：[72, 69, 79, 83, 82, 76]
 2.给students添加一行，索引为007，数据为："小杨", 79, 82, 81, 69
 3.输出students删除索引为006、007的结果，但不要改变students本身。
 4.输出students删除列名为“考试2”、“考试4”的结果，但不要改变students本身
 5.创建一个Seriesbonus，包含的值和值对应的索引分别为：{"考试1": 2, "考试2": 3, "考试3": 2, "考试4": 5}。输出这个Series与students里所有分数列相加后的结果，但不用更新students。
 6.更新students的考试4，让每项数据值增加10，并输出更新后的结果。

In [58]:
import pandas as pd

df1 = pd.DataFrame({"001": {"姓名": "小陈", "考试1": 85, "考试2": 95, "考试3": 92},
 "002": {"姓名": "小李", "考试1": 91, "考试2": 92, "考试3": 94},
 "003": {"姓名": "小王", "考试1": 86, "考试2": 81, "考试3": 89},
 "004": {"姓名": "小张", "考试1": 79, "考试2": 89, "考试3": 95},
 "005": {"姓名": "小赵", "考试1": 96, "考试2": 91, "考试3": 91},
 "006": {"姓名": "小周", "考试1": 81, "考试2": 89, "考试3": 92} })
df1 = df1.T
# print(df1)
df1.loc[:,['考试4']] = [72, 69, 79, 83, 82, 76]
# print(df1)
df1.loc['007'] =["小杨", 79, 82, 81, 69]
# print(df1)
print(df1.drop(['006','007']))
print(df1.drop(['考试1','考试2'],axis=1))
s1 = pd.Series({"考试1": 2, "考试2": 3, "考试3": 2, "考试4": 5})
print(s1+df1)
df1.loc[:,'考试4'] = df1.loc[:,'考试4']+10
print(df1)



     姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
     姓名 考试3  考试4
001  小陈  92   72
002  小李  94   69
003  小王  89   79
004  小张  95   83
005  小赵  91   82
006  小周  92   76
007  小杨  81   69
      姓名   考试1   考试2   考试3   考试4
001  NaN  87.0  98.0  94.0  77.0
002  NaN  93.0  95.0  96.0  74.0
003  NaN  88.0  84.0  91.0  84.0
004  NaN  81.0  92.0  97.0  88.0
005  NaN  98.0  94.0  93.0  87.0
006  NaN  83.0  92.0  94.0  81.0
007  NaN  81.0  85.0  83.0  74.0
     姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   82
002  小李  91  92  94   79
003  小王  86  81  89   89
004  小张  79  89  95   93
005  小赵  96  91  91   92
006  小周  81  89  92   86
007  小杨  79  82  81   79


### 函数赋值

创建一个名为students的DataFrame，包含数据如下：
{"001": {"姓名": "小陈", "考试1": 85, "考试2": 95, "考试3": 92},
 "002": {"姓名": "小李", "考试1": 91, "考试2": 92, "考试3": 94},
 "003": {"姓名": "小王", "考试1": 86, "考试2": 81, "考试3": 89},
 "004": {"姓名": "小张", "考试1": 79, "考试2": 89, "考试3": 95},
 "005": {"姓名": "小赵", "考试1": 96, "考试2": 91, "考试3": 91},
 "006": {"姓名": "小周", "考试1": 81, "考试2": 89, "考试3": 92}}
 1.创建一个叫student_average的DataFrame，索引为学号，包含姓名列（列名为“姓名”），以及计算出3次考试平均值后的结果列（列名为“平均分”）。
 2.输出每次考试第二高的分数组成的Series，可以尝试结合匿名函数。
 3.根据以下规则，输出每个学号对应的四次考试的等级：
 A+：平均分 >= 95
A：90 <= 平均分 < 95
B+：85 <= 平均分 < 90
B：80 <= 平均分 < 85
C+：75 <= 平均分 < 80
C：平均分 < 75
 4.展示students每个考试分数数据列的统计信息，包括个数、平均值、标准差、四分位数等。
 

In [129]:
import pandas as pd 
import numpy as np

students = pd.DataFrame({"001": {"姓名": "小陈", "考试1": 85, "考试2": 95, "考试3": 92},
 "002": {"姓名": "小李", "考试1": 91, "考试2": 92, "考试3": 94},
 "003": {"姓名": "小王", "考试1": 86, "考试2": 81, "考试3": 89},
 "004": {"姓名": "小张", "考试1": 79, "考试2": 89, "考试3": 95},
 "005": {"姓名": "小赵", "考试1": 96, "考试2": 91, "考试3": 91},
 "006": {"姓名": "小周", "考试1": 81, "考试2": 89, "考试3": 92}})
students = students.T
print(students.head())
student_average = pd.DataFrame({'姓名':students['姓名'],"平均分":students.loc[:,'考试1':'考试3'].mean(axis = 1)})
print(student_average)
print(students.loc[:,'考试1':'考试3'].apply(lambda x:sorted(x)[-2],axis = 0))

def fun_1(x):
    if x<60:
        return 'C'
    elif x<80:
        return 'B'
    else:
        return 'A'
students_1 = students.loc[:,'考试1':'考试3'].map(fun_1)
print(students_1.head())





     姓名 考试1 考试2 考试3
001  小陈  85  95  92
002  小李  91  92  94
003  小王  86  81  89
004  小张  79  89  95
005  小赵  96  91  91
     姓名        平均分
001  小陈  90.666667
002  小李  92.333333
003  小王  85.333333
004  小张  87.666667
005  小赵  92.666667
006  小周  87.333333
考试1    91
考试2    92
考试3    94
dtype: int64
    考试1 考试2 考试3
001   A   A   A
002   A   A   A
003   A   A   A
004   B   A   A
005   A   A   A


In [135]:
students['考试1'] = students['考试1'].astype('int')
students['考试2'] = students['考试2'].astype('int')
students['考试3'] = students['考试3'].astype('int')
students.info()
print(students.describe())

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 001 to 006
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   姓名      6 non-null      object
 1   考试1     6 non-null      int32 
 2   考试2     6 non-null      int32 
 3   考试3     6 non-null      int32 
dtypes: int32(3), object(1)
memory usage: 340.0+ bytes
             考试1        考试2        考试3
count   6.000000   6.000000   6.000000
mean   86.333333  89.500000  92.166667
std     6.314006   4.722288   2.136976
min    79.000000  81.000000  89.000000
25%    82.000000  89.000000  91.250000
50%    85.500000  90.000000  92.000000
75%    89.750000  91.750000  93.500000
max    96.000000  95.000000  95.000000
